version: '3.9'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - uxdebt-network

  backend:
    build:
      context: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - uxdebt-network

  frontend:
    build:
      context: ../UxDebt-front
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - uxdebt-network

volumes:
  postgres_data:

networks:
  uxdebt-network:
    driver: bridge