# Generated by Django 5.1.4 on 2024-12-17 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('code', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tag',
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('issue_id', models.AutoField(primary_key=True, serialize=False)),
                ('git_id', models.BigIntegerField(unique=True)),
                ('html_url', models.URLField()),
                ('status', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('discarded', models.BooleanField(default=False)),
                ('labels', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='api.repository')),
            ],
            options={
                'db_table': 'issue',
            },
        ),
        migrations.CreateModel(
            name='IssueTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_tags', to='api.issue')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_tags', to='api.tag')),
            ],
            options={
                'db_table': 'issue_tag',
                'unique_together': {('issue', 'tag')},
            },
        ),
    ]
