# Generated by Django 5.0.10 on 2024-12-20 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tag_issue_issuetag'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='tags',
            field=models.ManyToManyField(through='api.IssueTag', to='api.tag'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Abierto'), ('CLOSED', 'Cerrado'), ('ALL', 'Todos')], max_length=10),
        ),
    ]
