# Generated by Django 5.0.10 on 2024-12-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_tag_id_tag_tagid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
