# Generated by Django 4.2.20 on 2025-05-16 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_githubtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
