# Generated by Django 4.2.20 on 2025-05-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_issue_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='git_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
