# Generated by Django 4.2.20 on 2025-05-21 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_issue_git_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='repository',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='api.repository'),
        ),
    ]
