# Generated by Django 4.2.20 on 2025-09-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_issue_repository'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='html_url',
            field=models.URLField(null=True),
        ),
    ]
