# Generated by Django 4.2.20 on 2025-09-01 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_issue_html_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='html_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
