# Generated by Django 4.2.20 on 2025-09-09 19:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_issue_html_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='labels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
    ]
