# Generated by Django 4.2.20 on 2025-11-30 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_repository_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueTagPredicted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField(default=0.0)),
                ('rank', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicted_tags', to='api.issue')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicted_for_issues', to='api.tag')),
            ],
            options={
                'db_table': 'issue_tag_predicted',
                'unique_together': {('issue', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='tag_predicted',
            field=models.ManyToManyField(related_name='issues_predicted', through='api.IssueTagPredicted', to='api.tag'),
        ),
    ]
