# Generated by Django 4.2.20 on 2025-12-22 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_githubtoken_user_repository_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubtoken',
            name='token',
            field=models.CharField(max_length=255),
        ),
    ]
