# Generated by Django 4.2.20 on 2025-12-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_githubtoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='git_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='git_id',
            field=models.IntegerField(),
        ),
    ]
