# Generated by Django 4.2.20 on 2025-12-24 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_project_projectissue_issue_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='git_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
