# Generated by Django 4.2.20 on 2025-12-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_project_git_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
